server:
  port: 8082
  servlet:
    context-path: /producer
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.16.189:61616
    pool:
      enabled: true
      max-connections: 10
queueName: springboot-queue
topicName: springboot-topic