
package com.ly.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersionServiceImplService", targetNamespace = "http://impl.service.ly.com/", wsdlLocation = "http://localhost:8888/hello?wsdl")
public class PersionServiceImplService
    extends Service
{

    private final static URL PERSIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PERSIONSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.ly.com/", "PersionServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PERSIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PersionServiceImplService() {
        super(__getWsdlLocation(), PERSIONSERVICEIMPLSERVICE_QNAME);
    }

    public PersionServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public PersionServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PERSIONSERVICEIMPLSERVICE_QNAME);
    }

    public PersionServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public PersionServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersionServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersionServiceImpl
     */
    @WebEndpoint(name = "PersionServiceImplPort")
    public PersionServiceImpl getPersionServiceImplPort() {
        return super.getPort(new QName("http://impl.service.ly.com/", "PersionServiceImplPort"), PersionServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersionServiceImpl
     */
    @WebEndpoint(name = "PersionServiceImplPort")
    public PersionServiceImpl getPersionServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.ly.com/", "PersionServiceImplPort"), PersionServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PERSIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PERSIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
