
package com.ly.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersionServiceImpl", targetNamespace = "http://impl.service.ly.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersionServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersion", targetNamespace = "http://impl.service.ly.com/", className = "com.ly.service.impl.GetPersion")
    @ResponseWrapper(localName = "getPersionResponse", targetNamespace = "http://impl.service.ly.com/", className = "com.ly.service.impl.GetPersionResponse")
    @Action(input = "http://impl.service.ly.com/PersionServiceImpl/getPersionRequest", output = "http://impl.service.ly.com/PersionServiceImpl/getPersionResponse")
    public String getPersion(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
