server:
  port: 8083
  servlet:
    context-path: /consumer
spring:
  kafka:
    bootstrap-servers:
    - 192.168.16.189:9092
    - 192.168.16.190:9092
    consumer:
      group-id: consumer-default
      auto-commit-interval: 100
      #earliest 当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费
      #latest 当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据 
      #none topic各分区都存在已提交的offset时，从offset后开始消费；只要有一个分区不存在已提交的offset，则抛出异常
      auto-offset-reset: earliest
      enable-auto-commit: true #是否自动提交
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 3
      